#!/usr/bin/env bash
# script displays `To infinity and beyond` indefinitely with a sleep 2 in between each iteration, and `I am invincible!!!` when receiving a `SIGTERM` signal
i=1
while [$i=1]
do echo "To infinity and beyond"
	sleep 2
	trap "echo I am invincible!!!" SIGTERM
done
