#!/usr/bin/env bash
#print Best School 10 times, on line 9, print HI
i=1
while [ $i -le 10 ]
do
	if [ $i == 9 ]
	then
       		printf "Best School\n Hi \n"
		((i++))
	else
	       	echo "Best School"
		((i++))
	fi
done
