#!/usr/bin/env bash
#Code prints 1-20, prints bad luck on 4,9,17
i=1
while [ $i -le 20 ]
do
echo "$i"
((i++))
case "$i" in
	5) echo "bad luck from china";;
	10) echo "bad luck from japan";;
	18) echo "bad luck from italy";;
esac
done
